### PR TITLE
add option for passing directory containing sockets

### PR DESCRIPTION
**Pull request by klatys**
Hi, thanks for the exporter,
I'd suggest to you this extension for passing only directory containing .sock files.
It's useful for cases where you have several (tens, hundreds) of sockets and passing them all is simply an ordeal. Plus afaik there is 65k limit on command length, which could limit someone as well.

### CODE REVIEW

**Comment by Lusitaniae** [comment]
Hi Jan.

Thanks for the contribution, its looking good.

I think we should include additional validation to prevent these errors
```

 ./phpfpm_exporter --phpfpm.socket-directories /run/php/ --phpfpm.socket-directories /var/run/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x79c9ff]

goroutine 1 [running]:
main.main.func1(0xc420251280, 0x17, 0x0, 0x0, 0xa68e00, 0xc420254f00, 0x0, 0x0)
	/home/y/go/src/github.com/cdn77/phpfpm_exporter/phpfpm_exporter.go:274 +0x2f
path/filepath.walk(0xc420251100, 0x12, 0xa70980, 0xc42025b520, 0xc4200fc470, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.walk(0xc420246490, 0xd, 0xa70980, 0xc42025b450, 0xc4200fc470, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.walk(0x7ffea8b7a800, 0x9, 0xa70980, 0xc42006dc70, 0xc4200fc470, 0x0, 0x10)
	/usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0x7ffea8b7a800, 0x9, 0xc4200fc470, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:398 +0x14c
main.main()
	/home/y/go/src/github.com/cdn77/phpfpm_exporter/phpfpm_exporter.go:281 +0xd4b

```

**Comment by klatys** [comment]
Hi @Lusitaniae thanks for the suggestion, I'll gladly fix that, unfortunatelly I'm unable to reproduce that, any idea what might be causing the error?

**Comment by Lusitaniae** [comment]
HI Jan,

I'm using ubuntu and /var/run is the default location for socket listeners
I think.

So PHPFPM tries to connect to non phpfpm socket listeners and crashes.

Hope that helps,
Pedro

**Comment by klatys** [comment]
Hi Pedro,
that didn't occur to me thanks. I created a ubuntu server but still can't seem to be able to reproduce the bug.
Could you please try running the program with these lines so that we can find out which file/dir is causing the panic? (just above the condition [here](https://github.com/Lusitaniae/phpfpm_exporter/pull/5/files#diff-dbb7f002d62f151b0380173316b2ad77R274))
```
			fmt.Println(path)
			fmt.Println(info.Mode())
			fmt.Println(info.Mode()&os.ModeSocket == 0)
			fmt.Println(info.IsDir())
```
Thanks for the help Jan

**Comment by Lusitaniae** [comment]
```
/var/run/user
drwxr-xr-x
true
true
/var/run/user/1000
drwx------
true
true
/var/run/user/1000/dconf
drwx------
true
true
/var/run/user/1000/dconf/user
-rw-------
true
false
/var/run/user/1000/gvfs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x79caa2]

goroutine 1 [running]:
main.main.func1(0xc420257580, 0x17, 0x0, 0x0, 0xa68e00, 0xc42025aff0, 0x0, 0x0)
	/home/y/go/src/github.com/cdn77/phpfpm_exporter/phpfpm_exporter.go:275 +0xd2
path/filepath.walk(0xc420257400, 0x12, 0xa70980, 0xc420261c70, 0xc4200fc550, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.walk(0xc420262150, 0xd, 0xa70980, 0xc420261ba0, 0xc4200fc550, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.walk(0x7ffc712e8800, 0x9, 0xa70980, 0xc42006dee0, 0xc4200fc550, 0x0, 0x10)
	/usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0x7ffc712e8800, 0x9, 0xc4200fc550, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:398 +0x14c
main.main()
	/home/y/go/src/github.com/cdn77/phpfpm_exporter/phpfpm_exporter.go:285 +0xd4b

```


The output was quite extensive so I've copied only the end.

**Comment by klatys** [comment]
Ok `gvfs` is obviously something present on desktop only that's why I couldn't replicate it.

Could you try now please? I ran it on virtual ubuntu 16 and seems to be ok.

**Comment by Lusitaniae** [comment]
Thanks for the contribution Jan!

I've merged your PR

Also added a note on the readme suggesting people to use dedicated directories for PHP-FPM.

Because when I tested your new commit again with /var/run as socket-directory input, the exporter does not reply with results for a long time (I killed it after some moments) - but I think for real use cases it's not really important.

**Comment by klatys** [comment]
Hi Pedro, my pleasure. The note is definitely a good point. Thanks for that.
One more thing, would you please create a new release? Thanks!

**Comment by Lusitaniae** [comment]
Made a new release and is now being built by CircleCI.

Thanks for everything.

**Pull request merged**
